---

SSHD: sshd

RC_LOCAL_ATMO: /etc/rc.d/rc.local.atmo

PACKAGES:
  - epel-release
  - python26
  - zsh
  - tmux
  - screen
  - autoconf
  - gcc
  - make
  - tcsh
  - nss_ldap
  - patch
  - fuse
  - fuse-devel.x86_64
  - python
  - python-ldap

SYSLOG_SERVICE_NAME: syslog

# Add modules to be loaded here
#MODULES_TO_LOAD:
#  -
