INSTANCE_SCRIPT_DIR: /etc/atmo/instance-scripts.d
INSTANCE_SCRIPT_LOG_DIR: /var/log/atmo/instance-scripts
POST_SCRIPT_DIR: /etc/atmo/post-scripts.d
POST_SCRIPT_LOG_DIR: /var/log/atmo/post-scripts

POST_MAKE_DIRS:
  - "{{ POST_SCRIPT_DIR }}"
  - "{{ INSTANCE_SCRIPT_DIR }}"
  - "{{ POST_SCRIPT_LOG_DIR }}"
  - "{{ INSTANCE_SCRIPT_LOG_DIR }}"

RUN_SCRIPTS:
  - { log: "{{ INSTANCE_SCRIPT_LOG_DIR }}", dir: "{{ INSTANCE_SCRIPT_DIR }}" }
  - { log: "{{ POST_SCRIPT_LOG_DIR }}", dir: "{{ POST_SCRIPT_DIR }}" }
