---

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- fail:
    msg: "GUACAMOLE_SERVER_IP must be defined"
  when:
    - SETUP_GUACAMOLE is defined and SETUP_GUACAMOLE == true
    - GUACAMOLE_SERVER_IP is undefined

- name: Add Guacamole VNC configuration file
  template:
    src: 'config.guac.j2'
    dest: '/home/{{ ATMOUSERNAME }}/.vnc/config.guac'
  when:
    - has_gui
    - SETUP_GUACAMOLE is defined and SETUP_GUACAMOLE == true

- name: Add Guacamole VNC configuration file
  template:
    src: 'config.guac.j2'
    dest: '/home/{{ ATMOUSERNAME }}/.vnc/config.guac'

- name: Start VNC Server for Guacamole
  command: >
    /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/vncserver -config /home/{{ ATMOUSERNAME }}/.vnc/config.guac :5"
