---
# tasks to install RealVNC server on non-headless instances

- name: set environment variables for legacy systems
  set_fact: ansible_python_interpreter=/usr/bin/python
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags:
    - x

- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - x

# Only install RealVNC Server if VM is NOT headless
- name: verify that X server exists
  stat: path={{ XGUI.xsession_path }}
  register: xsession
  tags:
    - x

- name: verify that xterm session exists
  stat: path={{ XGUI.xterm_path }}
  register: xterm
  tags:
    - x

- name: set flag for GUI systems
  set_fact: has_gui={{ xsession.stat.exists and xterm.stat.exists }}
  tags:
    - x
    - shell_cmd
    - tar

# Perform install/config if NOT headless
- name: create needed directories
  # This is broken, `{{ item }}` is never used, only one directory is created
  file: path=/etc/vnc/config.d state=directory mode=0755
  with_items: '{{ XGUI.dirs_to_make }}'
  when: xsession.stat.exists and xterm.stat.exists

- name: install the dependencies for vncserver
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present
  with_items: '{{ XGUI.vnc_dependencies }}'
  when: xsession.stat.exists and xterm.stat.exists

- name: copy required files to remote host
  copy: src={{ item.FROM }} dest={{ item.TO }}
  with_items: '{{ XGUI.files_to_add }}'
  when: xsession.stat.exists and xterm.stat.exists

- name: 'custom configuration templated out'
  template:
    src: 'config.custom.j2'
    dest: '/etc/vnc/config.custom'
  when: has_gui

- name: install the package for vncserver if CentOS 5
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present disable_gpg_check=yes
  with_items: '{{ XGUI.packages }}'
  when: has_gui and (ansible_distribution == "CentOS") and (ansible_distribution_major_version == '5')

- name: install the package for vncserver if CentOS
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present {{ XGUI.extra_args }}
  with_items: '{{ XGUI.packages }}'
  when: has_gui and (ansible_distribution == "CentOS") and (ansible_distribution_major_version > '5')

- name: install the package for vncserver if Ubuntu
  action: >
    {{ ansible_pkg_mgr }} deb={{ item }} state=present {{ XGUI.extra_args }}
  with_items: '{{ XGUI.packages }}'
  when: xsession.stat.exists and xterm.stat.exists and ansible_distribution == "Ubuntu"

- block:
    - name: Copy desktop background to instance
      copy:
        src: "{{ background_img }}"
        dest: /usr/share/backgrounds/cloud_background.jpg

    - name: Change desktop background on CentOS
      become: yes
      become_user: "{{ ATMOUSERNAME }}"
      command: >
        gconftool-2 -s -t string /desktop/gnome/background/picture_filename "/usr/share/backgrounds/cloud_background.jpg"
      when: ansible_distribution == "CentOS"

    - name: Change desktop background on Ubuntu
      copy:
        src: /usr/share/backgrounds/cloud_background.jpg
        dest: /usr/share/backgrounds/default.jpg
        remote_src: True
      when: ansible_distribution == "Ubuntu"
  when: has_gui

- name: remove locks and un-needed files
  shell: /bin/rm -rf {{ item.PATH }}
  with_items: '{{ XGUI.files_to_remove }}'
  when: xsession.stat.exists and xterm.stat.exists

- name: create needed directories
  file: path={{ item.PATH }} state={{ item.STATE }} mode={{ item.MODE }}
  with_items: '{{ XGUI.dirs_to_make }}'
  when: xsession.stat.exists and xterm.stat.exists

- name: kill all running vncserver sessions
  shell: /bin/su {{ ATMOUSERNAME }} -c "/usr/bin/vncserver -kill :'{{ item }}'"
  with_items:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  failed_when: False
  tags:
    - kill-vnc

- name: Get Guacamole server IP address
  shell: >
    nslookup alom.iplantcollaborative.org | awk -F': ' 'NR==6 { print $2 }'
  register: guac_ip

- debug: msg="{{ guac_ip.stdout }}"

- name: Add Guacamole VNC configuration file
  template:
    src: 'config.guac.j2'
    dest: '/home/{{ ATMOUSERNAME }}/.vnc/config.guac'
  when: has_gui

- name: Add regular VNC configuration file
  template:
    src: 'config.reg.j2'
    dest: '/home/{{ ATMOUSERNAME }}/.vnc/config.reg'
  when: has_gui

- name: install license and start vncserver
  shell: "{{ item }}"
  with_items:
    - '/usr/bin/vnclicense -add {{ VNCLICENSE }}'
    - '/bin/su {{ ATMOUSERNAME }} -c /usr/bin/vncserver :1'
  when: xsession.stat.exists and xterm.stat.exists
  failed_when: False

- name: set environment variables for legacy systems
  set_fact: ansible_python_interpreter=/usr/bin/python26
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '6'
  tags:
    - x
