---

PACKAGE:
  to_remove:
    - firewalld

PROCESSES:
  to_kill:
    #- xscreensaver

SERVICES:
  enabled:
    - fail2ban
    - sshd
    - iptables
    - ntpd
  disabled:
    - cups
    - hplip
    - iscsi
    - bluetooth
    - hidd
    - isdn
    - avahi-daemon
