---

PACKAGE:
  to_remove:
    - xscreensaver

PROCESSES:
  to_kill:
    - xscreensaver

SERVICES:
  enabled:
    - fail2ban
    - ssh
    - ufw
    - ntp
  disabled:
    - cups
    - hplip
    - iscsi
    - bluetooth
    - hidd
    - isdn
    - avahi-daemon
