---

# Todo CentOS 6

- name: Allow-hotplug file templated
  template:
    src: 'allow-hotplug.cfg.j2'
    dest: '/etc/network/interfaces.d/allow-hotplug.cfg'
  when: 'ansible_distribution == "Ubuntu"'

- name: Interfaces bounced
  shell: 'ifdown {{ item }} ; ifup {{ item }}'
  with_items: {{ ansible_interfaces | reject("equalto", "lo") }}
  when: 'ansible_distribution == "Ubuntu"'
