---

- name: Checking for necessary --extra_vars
  hosts: all
  vars:
    example:
      - "-e \"{'VOLUME_DEVICE':'/dev/sdb', 'VOLUME_DEVICE_TYPE': 'ext4'}\""

  tasks:

    - fail: msg="Variable VOLUME_DEVICE is not set."
      when: VOLUME_DEVICE is not defined

    - fail: msg="Variable VOLUME_DEVICE_TYPE is not set."
      when: VOLUME_DEVICE_TYPE is not defined


- name: Play to ensure filesystem is present before mounting
  hosts: all
  roles:
    - atmo-mkfs-volume
