--- 
- name: get atmo vm ip address
  set_fact: vm_ip="{{ ansible_host }}"

- debug: msg="Atmo VM IP is {{ vm_ip }}"

- name: verify that host is reachable via ssh port
  local_action: wait_for
      search_regex=OpenSSH
      port={{ ansible_port }}
      host="{{ vm_ip }}"
      delay=1
      timeout={{ SSH_PORT_TIMEOUT }}
  tags: verify-ssh

- name: test default ansible connection
  local_action: "shell ssh -p {{ ansible_port }} root@{{ vm_ip }} 'echo hello' | grep 'hello'"
  register: default_remote_user
  ignore_errors: yes
  failed_when: False
  async: "{{ SSH_TIMEOUT }}"
  poll: 1

###
# CENTOS SETUP
###
- name: test centos connection
  local_action: "shell ssh -p {{ ansible_port }} centos@{{ vm_ip }} 'echo hello' | grep 'hello'"
  register: centos_remote_user
  ignore_errors: yes
  when: default_remote_user|failed
  failed_when: False
  async: "{{ SSH_TIMEOUT }}"
  poll: 1

###
# UBUNTU SETUP
###
- name: test ubuntu connection
  local_action: "shell ssh -p {{ ansible_port }} ubuntu@{{ vm_ip }} 'echo hello' | grep 'hello'"
  register: ubuntu_remote_user
  ignore_errors: yes
  when: default_remote_user|failed and centos_remote_user|failed
  failed_when: False
  async: "{{ SSH_TIMEOUT }}"
  poll: 1

# - debug: msg="root output is {{ default_remote_user.stdout }} and err is {{ default_remote_user.stderr }}"
# 
# - debug: msg="centos output is {{ centos_remote_user.stdout }} and err is {{ centos_remote_user.stderr }}"
#   when: default_remote_user|failed
# 
# - debug: msg="ubuntu output is {{ ubuntu_remote_user.stdout }} and err is {{ ubuntu_remote_user.stderr }}"
#   when: default_remote_user|failed and centos_remote_user|failed

- name: fail when ssh errors occur related to Host key verification failed.
  fail:
    msg: "Configuration Error: Host key verification failed for IP: {{vm_ip}} . Does your ssh/config have 'StrictHostKeyChecking no' for the IP/IP Range/*"
  when: (default_remote_user.stderr is defined and default_remote_user.stderr == "Host key verification failed.") and
        (centos_remote_user.stderr is defined and centos_remote_user.stderr == "Host key verification failed.") and
        (ubuntu_remote_user.stderr is defined and ubuntu_remote_user.stderr == "Host key verification failed.")

- name: fail when ssh not possible
  fail: msg="The host is not reachable via SSH as root and cloud users."
  when: (default_remote_user.stdout is defined and default_remote_user.stdout != "hello") and
        (centos_remote_user.stdout is defined and centos_remote_user.stdout != "hello") and
        (ubuntu_remote_user.stdout is defined and ubuntu_remote_user.stdout != "hello")
