---
# ansible-playbook playbooks/utils/mount_volume.yml -i hosts --limit "vm0" -e "{'name':'/vol1', 'src':'/dev/vdc', 'fstype': 'ext3' }"

# CentOS 4!?
- set_fact:
    ansible_python_interpreter: '/usr/bin/python2.6'
  when: 'ansible_distribution == "CentOS" and ansible_distribution_major_version < "5"'

- debug:
    var: item.mount
  with_items:
    - ansible_mounts

- set_fact:
    already_mounted: true
  when: 'item.mount == {{ name }}'
  with_items: '{{ ansible_mounts }}'

- debug:
    var: already_mounted

- name: Fail when device src given does not exists
  fail:
    msg: 'device src given does not exist'
  when: 'ansible_devices.{{ src | basename }} is undefined'

- name: 'mount volume to {{ name }}'
  mount:
    name: '{{ name }}'
    src: '{{ src }}'
    fstype: '{{ fstype }}'
    state: 'mounted'
  when: '(ansible_devices.{{ src | basename }} is defined) and (already_mounted is not defined)'
