---
galaxy_info:
  author: Calvin Mclean
  description: Installs kanki-irodsclient.
  company: CyVerse
  license: BSD
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  galaxy_tags:
    - installer
    - iRods

dependencies: []
