# tasks to install irods
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  tags: vars

- name: copy over irods executables
  copy: src={{ IRODS_EXECUTABLE }} dest={{ IRODS_DESTINATION }} mode=a+x

- name: create additional symlink
  file: src={{ IRODS_DESTINATION }} dest={{ IRODS_LINK }} state=link

- name: copy over icommands
  unarchive: src={{ ICOMMANDS_TAR }} dest={{ ICOMMANDS_DESTINATION }} copy=yes creates=yes

- name: register list of files
  shell: ls -1 {{ ICOMMANDS_DESTINATION }}/icommands
  register: contents

- name: link icommand executables to bin path
  file: src={{ ICOMMANDS_DESTINATION }}/icommands/{{ item }} dest={{ BIN_PATH }}/{{ item }} state=link
  with_items: contents.stdout_lines
