---

# Required roles from Ansible Galaxy
# Install latest version of required Ansible roles by running the following:
# ansible-galaxy install -f -r requirements.yml -p roles/

- src: CyVerse-Ansible.irods-icommands
  name: irods-icommands

- src: CyVerse-Ansible.atmo-backup
  name: atmo-backup

- src: CyVerse-Ansible.ez
  name: ez

- src: CyVerse-Ansible.kanki-irodsclient
  name: atmo-kanki-irodsclient

- src: CyVerse-Ansible.add-user
  name: add-user

- src: CyVerse-Ansible.remove-user
  name: remove-user