- name: 'Python interpreter set for CentOS 5'
  set_fact:
    ansible_python_interpreter: '/usr/bin/python'
  when: 'ansible_distribution == "CentOS" and ansible_distribution_major_version == "5"'
  tags:
    - 'python'

- name: 'OS-specific variables gathered'
  include_vars: '{{ item }}'
  with_first_found:
    - '../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '../vars/{{ ansible_distribution }}.yml'
    - '../vars/{{ ansible_os_family }}.yml'

- name: 'atmo-dhcp - DHCP log directory created'
  file:
    path: '{{ LOG_PATH }}'
    state: 'directory'

- name: 'atmo-dhcp - DHCP log file created'
  file:
    path: '{{ LOG_PATH }}/{{ LOG_FILE_NAME }}'
    state: 'touch'
    mode: 0744
  # The following two lines work around https://github.com/ansible/ansible-modules-core/issues/170
  register: 'touch_log'
  changed_when: 'touch_log.diff.before.state != "file"'

- name: 'atmo-dhcp - DHCP script templated to target'
  template:
    src: 'hostname-exit-hook.sh.j2'
    dest: '{{ DHCP_DESTINATION }}'
    mode: 0755
  tags:
    - 'copy-dhcp'

- name: 'atmo-dhcp - hostname update script manually executed'
  shell: '{{ DHCP_DESTINATION }}'
  tags:
    - 'set-hostname'
