---
galaxy_info:
  author: Calvin Mclean
  description: Adds a script to user's path for backing up instance.
  company: CyVerse
  license: BSD
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  galaxy_tags:
    - cyverse
    - backup

dependencies: []
